/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as IndexRouteImport } from './app/index'
import { Route as AboutRouteImport } from './app/about'
import { Route as ProjectsCodingRouteImport } from './app/projects/coding'
import { Route as ProjectsVideoRouteImport } from './app/projects/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCodingRoute = ProjectsCodingRouteImport.update({
  id: '/projects/coding',
  path: '/projects/coding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsVideoRoute = ProjectsVideoRouteImport.update({
  id: '/projects/video',
  path: '/projects/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/coding': typeof ProjectsCodingRoute
  '/projects/video': typeof ProjectsVideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/coding': typeof ProjectsCodingRoute
  '/projects/video': typeof ProjectsVideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/projects/coding': typeof ProjectsCodingRoute
  '/projects/video': typeof ProjectsVideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/projects/coding' | '/projects/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/projects/coding' | '/projects/video'
  id: '__root__' | '/' | '/about' | '/projects/coding' | '/projects/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProjectsCodingRoute: typeof ProjectsCodingRoute
  ProjectsVideoRoute: typeof ProjectsVideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/coding': {
      id: '/projects/coding'
      path: '/projects/coding'
      fullPath: '/projects/coding'
      preLoaderRoute: typeof ProjectsCodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/video': {
      id: '/projects/video'
      path: '/projects/video'
      fullPath: '/projects/video'
      preLoaderRoute: typeof ProjectsVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProjectsCodingRoute: ProjectsCodingRoute,
  ProjectsVideoRoute: ProjectsVideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
